# Generated by Django 2.0.8 on 2018-09-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_sell',
            field=models.CharField(default=300, max_length=100),
            preserve_default=False,
        ),
    ]
